// Generated by LiveScript 1.2.0
var ctx, gui, scene, lastTick, tick, render;
window.ORB = {
  TICK_INTERVAL_MS: 1000 / 60
};
window.requestAnimFrame = window.requestAnimationFrame || window.webkitRequestAnimationFrame || window.mozRequestAnimationFrame || function(callback){
  window.setTimeout(callback, window.ORB.TICK_INTERVAL_MS);
};
window.ORB.main = (ctx = null, gui = {
  keyDown: function(){},
  keyUp: function(){},
  render: function(){}
}, scene = {
  keyDown: function(){},
  keyUp: function(){},
  tick: function(){},
  render: function(){}
}, lastTick = Date.now(), tick = function(){
  var now;
  setTimeout(tick, ORB.TICK_INTERVAL_MS);
  now = Date.now();
  scene.tick(now - lastTick);
  lastTick = now;
}, render = function(){
  requestAnimFrame(render);
  ctx.fillStyle = 'black';
  ctx.fillRect(0, 0, ctx.canvas.width, ctx.canvas.height);
  scene.render(ctx);
  gui.render(ctx);
}, function(){
  var canvas;
  canvas = document.getElementById('canvas');
  ctx = canvas.getContext('2d');
  ctx.font = '20pt Tahoma';
  document.body.addEventListener('keydown', function(it){
    gui.keyDown(it.keyCode) || scene.keyDown(it.keyCode);
  });
  document.body.addEventListener('keyup', function(it){
    return gui.keyUp(it.keyCode) || scene.keyUp(it.keyCode);
  });
  setTimeout(tick, ORB.TICK_INTERVAL_MS);
  return requestAnimFrame(render);
});