// Generated by LiveScript 1.2.0
this.ORB = {
  TICK_INTERVAL_MS: 1000 / 60
};
this.requestAnimFrame = this.requestAnimationFrame || this.webkitRequestAnimationFrame || this.mozRequestAnimationFrame || function(callback){
  this.setTimeout(callback, this.ORB.TICK_INTERVAL_MS);
};
this.ORB.main = function(){
  var ctx, gui, scene, lastTick, tick, render;
  ctx = null;
  gui = {
    keyDown: function(){},
    keyUp: function(){},
    render: function(){}
  };
  scene = null;
  lastTick = Date.now();
  tick = function(){
    var now;
    setTimeout(tick, ORB.TICK_INTERVAL_MS);
    now = Date.now();
    scene.tick(now - lastTick);
    lastTick = now;
  };
  render = function(){
    requestAnimFrame(render);
    ctx.fillStyle = 'black';
    ctx.fillRect(0, 0, ctx.canvas.width, ctx.canvas.height);
    scene.render(ctx);
    gui.render(ctx);
  };
  return function(){
    var canvas;
    canvas = document.getElementById('canvas');
    ctx = canvas.getContext('2d');
    ctx.font = '20pt Tahoma';
    scene = new ORB.Space();
    document.body.addEventListener('keydown', function(it){
      gui.keyDown(it.keyCode) || scene.keyDown(it.keyCode);
    });
    document.body.addEventListener('keyup', function(it){
      return gui.keyUp(it.keyCode) || scene.keyUp(it.keyCode);
    });
    setTimeout(tick, ORB.TICK_INTERVAL_MS);
    return requestAnimFrame(render);
  };
}();