// Generated by LiveScript 1.2.0
'use strict';
var List;
window.log = function(it){
  return console.log(it);
};
window.err = function(it){
  return console.err(it);
};
window.List = List = (function(){
  List.displayName = 'List';
  var prototype = List.prototype, constructor = List;
  function List(){
    this.size = 0;
  }
  prototype.add = function(element){
    if (element) {
      this.tail = this.tail
        ? this.tail.next = {
          e: element
        }
        : this.head = {
          e: element
        };
      this.size++;
    }
    return element;
  };
  prototype.poll = function(){
    var element;
    element = this.head ? this.head.e : undefined;
    if (element) {
      this.head = this.head === this.tail
        ? this.tail = undefined
        : this.head.next;
      this.size--;
    }
    return element;
  };
  prototype.remove = function(element){
    var node;
    if (!element) {
      return false;
    }
    if (this.head === element) {
      this.head = this.head === this.tail
        ? this.tail = undefined
        : this.head.next;
      this.size--;
      return true;
    }
    node = this.head.next;
    while (node.next.next) {
      if (node.next === element) {
        node.next = node.next.next;
        this.size--;
        return true;
      }
      node = node.next;
    }
    if (this.tail === element) {
      this.tail = node;
      this.size--;
      return true;
    }
    return false;
  };
  return List;
}());